# -*- coding: utf-8 -*-
"""BBands_Crypto

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zJKbfUzkORX-2qKMEilsVUfYO4WMhM73
"""

!pip install yfinance

!pip install mplfinance

import pandas as pd
import yfinance as yf
import mplfinance as mpf

start = '2021-01-01'

data = yf.download('BTC-USD', start=start)

data

def get_bbands(df, period):
  df = data.copy()
  df['sma'] = data.Close.rolling(period).mean()
  df['upper'] = data.Close.rolling(period).mean() + (2*data.Close.rolling(period).std())
  df['lower'] = data.Close.rolling(period).mean() - (2*data.Close.rolling(period).std())

  return df

df = get_bbands(data, 20)

df

apd = mpf.make_addplot(df[['upper','lower','sma']])

mpf.plot(df, type='candle', style='yahoo', addplot=apd, title='Bitcoin Bollinger Bands', figsize=(11,6))

def get_ebbands(data, period):
  df2 = data.copy()
  df2['ema'] = data.Close.ewm(span=period, adjust=False, min_periods=period).mean()
  df2['upper'] = data.Close.ewm(span=period, adjust=False, min_periods=period).mean() + (2*data.Close.ewm(span=period, adjust=False, min_periods=period).std())
  df2['lower'] = data.Close.ewm(span=period, adjust=False, min_periods=period).mean() - (2*data.Close.ewm(span=period, adjust=False, min_periods=period).std())

  return df2

df2 = get_ebbands(data, 20)

apd2 = mpf.make_addplot(df2[['upper','lower','ema']])

mpf.plot(df2, type='candle', style='yahoo', addplot=apd2, title='Bitcoin Bollinger Bands', figsize=(11,6))

