# -*- coding: utf-8 -*-
"""Investic-Return_rev_a

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/178Yg0vm-NztwYQCIaLhoxkHNxQCf9NGv
"""

!pip install yfinance

import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf

start = '2019-01-01'
end = '2021-01-01'

tsla = yf.download('TSLA', start=start, end=end)

tsla



price = tsla['Adj Close']

ret_manual = price/price.shift(1) - 1

ret_manual

ret = price.pct_change()

ret



#Backward Return

m3b_ret = price.pct_change(60)

m6b_ret = price.pct_change(126)

y_ret = price.pct_change(252)

#Forward Return

three_month_ret = price.pct_change(-60)

six_month_ret = price.pct_change(-126)

one_year_ret = price.pct_change(-252)

"""หาราคาหุ้น เป็นรายสัปดาห์ เริ่มต้นวันจันทร์"""

weekly_price = price.asfreq('W-Mon')

weekly_price

weekly_ret = weekly_price.pct_change()

"""หาราคาหุ้น เป็นรายสัปดาห์ ปกติเราจะใช้วันศุกร์"""

weekly_price = price.asfreq #(<ลองเปลี่ยนเป็นวันศุกร์>)

"""หาราคาหุ้น เป็นรายเดือน"""

monthly_price = price.resample('M').last()

monthly_price

monthly_ret = monthly_price.pct_change()

monthly_ret

