# -*- coding: utf-8 -*-
"""Investic - Volatility_rev_a

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LggBJKT-Q2_0FB-SshxZUfIuQbW8bQcJ
"""

!pip install yfinance

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf

start = '2016-01-01'
end = '2021-01-01'

AAPL = yf.download('AAPL', start=start, end=end)
AAPL



price = AAPL['Adj Close']

ret = price.pct_change()

weekly_price = price.asfreq('W-FRI')

weekly_ret = weekly_price.pct_change()

weekly_ret

vol_d = ret.std()*np.sqrt(252)
vol_d

vol_w = weekly_ret.std()*np.sqrt(52) 
vol_w

"""3M Volatility (Annualized from Daily)"""

vol_d_rolling = ret.rolling(window=60).std()*np.sqrt(252)
vol_d_rolling

vol_d_rolling.plot()

"""3M Volatility (Annualized from Weekly)"""

vol_w_rolling = weekly_ret.rolling(window=12).std()*np.sqrt(52)
vol_w_rolling

vol_w_rolling.plot()

"""ลองทำ เป็น Monthly ดูนะครับ  เปลี่ยนเป็น 12"""

