# -*- coding: utf-8 -*-
"""Resample Aggregrate

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_JYBhwfAmzIZZsjFhQ0UEgHGYx7udDmH
"""

!pip install yfinance

import pandas as pd
import yfinance as yf

data = yf.download('TSLA', start='2021-01-06', end='2022-01-01')

data.tail()

data.resample('W-Mon').last()

df_weekly = data.resample('W-FRI').agg({'Open':'first',
                                    'High':'max',
                                    'Low':'min',
                                    'Close':'last',
                                    'Volume':'sum'})

df_weekly

df_monthly = data.resample('BM').agg({'Open':'first',
                                      'High':'max',
                                      'Low':'min',
                                      'Close':'last',
                                      'Volume':'sum'})

df_monthly

data.resample('D').last()

df_everyday = data.resample('D').last()

df_everyday.fillna(method='ffill', inplace=True)

df_everyday

df_businessday = df_everyday.resample('B').last()
df_businessday

df_weekly.head()

df_weekly['next_week_closing'] = df_weekly['Close'].shift(-1)
df_weekly.tail()

df_weekly['weekly_return'] = df_weekly['Close'].pct_change(-1)
df_weekly.head()