# -*- coding: utf-8 -*-
"""Workshop - Price Condition

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NrDEnNLgnvdTX9ppb7JOK6BPCRftShje
"""

!pip install yfinance

import pandas as pd
import yfinance as yf

data = yf.download('BTC-USD', start='2021-01-01', end='2022-05-01')

data

df = data.copy()

df['Return'] = df['Close'].pct_change()

df

"""#ข้อที่ 1 Filter ราคาปิดที่มีค่ามากกว่า 60,000 USD"""

df[df.Close > 60000]

"""#ข้อที่ 2 Filter Return ที่มีค่ามากกว่า 0 """

df[df['Return'] > 0]

"""#ข้อ 3 สร้าง Function แล้วให้ Print โดยมี Condition ที่ว่าหาก Return > 0 ให้ Print "Gain" หาก Return < 0 ให้ปริ้น "Loss"
"""

def ret_con(df):
  if (df > 0):
    print('Gain')

  elif (df < 0):
    print('Loss')

for i in range(len(df.Close)):
  ret_con(df.iloc[i,-1])



"""#แถม"""

sum1 = len(df.loc[(df['Return'] < 0)])
sum2 = len(df.loc[(df['Return'] > 0)])

sum = len(df.Return)

per1 = (sum1/sum *100)
per2 = (sum2/sum *100)

print("Number of expected loss are {0} times in {1} about {2:.2f}%".format(sum1,sum, per1))

print('Number of expected gain are {0} times in {1} about {2:.2f}%'.format(sum2, sum, per2))

